### ISSUE TITLE
Mod Suggestions

### ISSUE THREAD

**Issue by Hexblood** [MunsterMc/Mun-s-Pixelmon#1]
**Mods I would really like to see** (Mostly QoL enhancements)

**Apple Skin** ~ https://www.curseforge.com/minecraft/mc-mods/appleskin
- Shows more on tool tip and hunger bar about the food. Web page explains it quite well with pictures.

**Bed Patch** ~ https://www.curseforge.com/minecraft/mc-mods/bed-patch
- Fixes a Vanilla bug that causes players to get stuck in their bed.

**Find Me** ~ https://www.curseforge.com/minecraft/mc-mods/findme
- Hover over an item in JEI and press the key bind and any chest with that item in it will be highlighted for a short time.

**HWYLA** ~ https://www.curseforge.com/minecraft/mc-mods/hwyla
- If you are familiar with Waila it is the same thing for newer versions. Adds a tool tip to the top of the screen giving information about the block or entity you are looking at. It can be hidden for players that do not want it. 
- **Waila Harvestability** ~ https://www.curseforge.com/minecraft/mc-mods/waila-harvestability
    Addon that shows additional information like if you are using the right tool to mine a block or if it can be silk touched or sheared.

**Journey Map** ~ https://www.curseforge.com/minecraft/mc-mods/journeymap
- I did just see a comment somewhere claiming the Technic people may not be allowing the mod on their service for some stupid reason. Last time I tried it worked client side. So I can try just running it for myself. However others may find it useful as well so manually adding it might not be to bad of an idea.

**Controlling** ~ https://www.curseforge.com/minecraft/mc-mods/controlling
- Adds search options to the Controls menu making it easier to sort out key bind conflicts.

**Nether Portal Fix** ~ https://www.curseforge.com/minecraft/mc-mods/netherportalfix
- Fixes the way Nether Portals connect. Reducing, if not eliminating, the chances of a Portal connecting with one hundreds of blocks away.

**Quick Leaf Decay** ~ https://www.curseforge.com/minecraft/mc-mods/quick-leaf-decay
- Leaves decay as soon as the tree is cut down. No more floating leaf blocks hanging around for days. Since you have TreeCapitator and TiCon this might be nice to have as well.

**Mods that add stuff to the game**

**Corail Tombstone** ~ https://www.curseforge.com/minecraft/mc-mods/corail-tombstone
- When a player dies their items are placed in a grave and they respawn with a key to unlock it and get their items back. It has some other features that will be less useful for a Pixelmon server but as far as the graves go it is one of the better ones. There is an option for crafting the key with an ender pearl and it will teleport you to the grave. (Can be disabled if wanted)

**Enchanting Plus** ~ https://www.curseforge.com/minecraft/mc-mods/enchanting-plus
- Adds and enhanced Enchanting table that lets you pick the enchantments to be applied. I have noticed with Pixelmon it is harder to get player levels. It would be nice to be able to get the enchantments we want without playing the random game that Vanilla offers.

**Iron Chests** ~ https://www.curseforge.com/minecraft/mc-mods/iron-chests
- Bigger chests and Shulker Boxes

**Improved Backpacks** ~ https://www.curseforge.com/minecraft/mc-mods/improvedbackpacks
- Upgrade able and wearable backpacks. Can go in either Chestplate or a Baubles slot.
- **Baubles** ~ https://www.curseforge.com/minecraft/mc-mods/baubles

**Simple Storage Network** ~ https://www.curseforge.com/minecraft/mc-mods/simple-storage-network
- Connect all of your storage to a central terminal and craft from there. (Does not require power)

**Storage Drawers** ~ https://www.curseforge.com/minecraft/mc-mods/storage-drawers
- Upgrade able bulk storage. Need someplace to store 32 or more stacks of something?

**Uppers** ~ https://www.curseforge.com/minecraft/mc-mods/uppers
- Opposite of a hopper. Pulls items from below and puts them up or to the side.

**XP from Harvest** ~ https://www.curseforge.com/minecraft/mc-mods/xp-from-harvest
- Gain XP from harvesting crops. Once again player XP is harder to come by in Pixelmon so I find having another method to be a good thing. It also has a config option for right click harvest and replant in one action.

**Wonder Trade** ~https://pixelmonmod.com/downloads.php
- I am playing with this on my single player world. Basically it generates a pool of random Pokemon. When a player runs the command a Pokemon of their choosing will go into the pool and they receive a random one in exchange. By default it is on a 1 hr cooldown for that player till it can be used again. It does have a confirmation process so there is no accidental loss of Pokemon you may want to keep without being a dumb-dumb. It is something a little fun to do with the less than desired catches.

**Comment by Hexblood** [comment]
Just remembered a different mapping mod I have used before.

**Xaero's Minimap** ~ https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap

**Xaero's World Map** ~ https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map

**Comment by MunsterMc** [comment]
QoL mods are being added currently, JourneyMap is already in the pack.
Will add a couple of the other mods though
